### ISSUE TITLE
Add support for retiming and blending without shortcutting

### ISSUE THREAD

**Issue by mkoval** [personalrobotics/or_parabolicsmoother#6]
We should add parameters for: (1) disable shortcutting and (2) disable blending. Once these are in place, `HauserParabolicSmoother` is a drop-in replacement for the planners built-in to OpenRAVE.

**Comment by psigen** [comment]
@mkoval: Didn't you add this already? https://github.com/personalrobotics/or_parabolicsmoother/commit/71557eaabebb46e6a9aaa9eb9becd7e5a5be8441

**Comment by mkoval** [comment]
Yes, this was implemented in 71557ea.
